"""
Slot model.

Concrete, materialised appointment time slots.
Generated by the slot engine from Availability records.

CRITICAL CONSTRAINTS:
  - UNIQUE(doctor_id, slot_start) — prevents duplicate slot creation
  - UNIQUE via appointments(slot_id) — prevents double booking

All timestamps stored in UTC. API layer converts to IST for presentation.
"""

import uuid
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base

if TYPE_CHECKING:
    from app.models.doctor import Doctor
    from app.models.availability import Availability
    from app.models.appointment import Appointment


class Slot(Base):
    __tablename__ = "slots"

    __table_args__ = (
        # PRIMARY double-booking guard at DB level
        UniqueConstraint("doctor_id", "slot_start", name="uq_doctor_slot"),
        CheckConstraint("slot_end > slot_start", name="ck_slot_valid_window"),
        # Partial index: fast lookup of available slots per doctor
        Index(
            "ix_slots_doctor_available",
            "doctor_id",
            "slot_start",
            postgresql_where="is_available = true",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    doctor_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("doctors.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    availability_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("availability.id", ondelete="CASCADE"),
        nullable=False,
    )
    # Stored in UTC
    slot_start: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, index=True
    )
    slot_end: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    is_available: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=True, index=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    # ── Relationships ─────────────────────────────────────────────────────
    doctor: Mapped["Doctor"] = relationship(  # noqa: F821
        "Doctor", back_populates="slots"
    )
    availability: Mapped["Availability"] = relationship(  # noqa: F821
        "Availability", back_populates="slots"
    )
    appointment: Mapped["Appointment | None"] = relationship(  # noqa: F821
        "Appointment",
        foreign_keys="[Appointment.slot_id]",
        back_populates="slot",
        uselist=False,
    )

    def __repr__(self) -> str:
        status = "available" if self.is_available else "booked"
        return (
            f"<Slot id={self.id} doctor_id={self.doctor_id} "
            f"start={self.slot_start} [{status}]>"
        )
